server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: micro1
          uri: http://localhost:8081/
          predicates:
          - Path=/producer/**
        - id: micro2
          uri: http://localhost:8082/
          predicates:
          - Path=/micro2/**
        - id: rest
          uri: http://localhost:8084/
          predicates:
          - Path=/excel/**